# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_libs',
            name='full_text',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='saved_libs',
            name='original_text',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='user_submission',
            name='text',
            field=models.CharField(max_length=5000),
        ),
    ]
