# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cjangoApp', '0005_auto_20180129_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved_libs',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='user_submission',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='saved_libs',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_submission',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
