# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cjangoApp', '0009_auto_20180129_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_libs',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user_submission',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
