# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cjangoApp', '0010_auto_20180129_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_libs',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='user_submission',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
